"""baseline

Revision ID: 2db811e78daf
Revises: 
Create Date: 2026-03-07 22:38:39.231648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2db811e78daf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_system_attributes')
    op.drop_table('study_user_attributes')
    op.drop_index(op.f('ix_trials_study_id'), table_name='trials')
    op.drop_table('trials')
    op.drop_table('trial_intermediate_values')
    op.drop_table('trial_params')
    op.drop_table('study_directions')
    op.drop_table('study_system_attributes')
    op.drop_table('version_info')
    op.drop_table('trial_heartbeats')
    op.drop_table('trial_user_attributes')
    op.drop_table('trial_values')
    op.drop_index(op.f('ix_studies_study_name'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('study_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('study_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('study_id', name=op.f('studies_pkey'))
    )
    op.create_index(op.f('ix_studies_study_name'), 'studies', ['study_name'], unique=True)
    op.create_table('trial_values',
    sa.Column('trial_value_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('objective', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_type', postgresql.ENUM('FINITE', 'INF_POS', 'INF_NEG', name='trialvaluetype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], name=op.f('trial_values_trial_id_fkey')),
    sa.PrimaryKeyConstraint('trial_value_id', name=op.f('trial_values_pkey')),
    sa.UniqueConstraint('trial_id', 'objective', name=op.f('trial_values_trial_id_objective_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trial_user_attributes',
    sa.Column('trial_user_attribute_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('value_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], name=op.f('trial_user_attributes_trial_id_fkey')),
    sa.PrimaryKeyConstraint('trial_user_attribute_id', name=op.f('trial_user_attributes_pkey')),
    sa.UniqueConstraint('trial_id', 'key', name=op.f('trial_user_attributes_trial_id_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trial_heartbeats',
    sa.Column('trial_heartbeat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('heartbeat', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], name=op.f('trial_heartbeats_trial_id_fkey')),
    sa.PrimaryKeyConstraint('trial_heartbeat_id', name=op.f('trial_heartbeats_pkey')),
    sa.UniqueConstraint('trial_id', name=op.f('trial_heartbeats_trial_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('version_info',
    sa.Column('version_info_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('library_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.CheckConstraint('version_info_id = 1', name=op.f('version_info_version_info_id_check')),
    sa.PrimaryKeyConstraint('version_info_id', name=op.f('version_info_pkey'))
    )
    op.create_table('study_system_attributes',
    sa.Column('study_system_attribute_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('value_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('study_system_attributes_study_id_fkey')),
    sa.PrimaryKeyConstraint('study_system_attribute_id', name=op.f('study_system_attributes_pkey')),
    sa.UniqueConstraint('study_id', 'key', name=op.f('study_system_attributes_study_id_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('study_directions',
    sa.Column('study_direction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('direction', postgresql.ENUM('NOT_SET', 'MINIMIZE', 'MAXIMIZE', name='studydirection'), autoincrement=False, nullable=False),
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('objective', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('study_directions_study_id_fkey')),
    sa.PrimaryKeyConstraint('study_direction_id', name=op.f('study_directions_pkey')),
    sa.UniqueConstraint('study_id', 'objective', name=op.f('study_directions_study_id_objective_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trial_params',
    sa.Column('param_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('param_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distribution_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], name=op.f('trial_params_trial_id_fkey')),
    sa.PrimaryKeyConstraint('param_id', name=op.f('trial_params_pkey')),
    sa.UniqueConstraint('trial_id', 'param_name', name=op.f('trial_params_trial_id_param_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trial_intermediate_values',
    sa.Column('trial_intermediate_value_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intermediate_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intermediate_value_type', postgresql.ENUM('FINITE', 'INF_POS', 'INF_NEG', 'NAN', name='trialintermediatevaluetype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], name=op.f('trial_intermediate_values_trial_id_fkey')),
    sa.PrimaryKeyConstraint('trial_intermediate_value_id', name=op.f('trial_intermediate_values_pkey')),
    sa.UniqueConstraint('trial_id', 'step', name=op.f('trial_intermediate_values_trial_id_step_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trials',
    sa.Column('trial_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', postgresql.ENUM('RUNNING', 'COMPLETE', 'PRUNED', 'FAIL', 'WAITING', name='trialstate'), autoincrement=False, nullable=False),
    sa.Column('datetime_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('datetime_complete', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('trials_study_id_fkey')),
    sa.PrimaryKeyConstraint('trial_id', name=op.f('trials_pkey'))
    )
    op.create_index(op.f('ix_trials_study_id'), 'trials', ['study_id'], unique=False)
    op.create_table('study_user_attributes',
    sa.Column('study_user_attribute_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('value_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('study_user_attributes_study_id_fkey')),
    sa.PrimaryKeyConstraint('study_user_attribute_id', name=op.f('study_user_attributes_pkey')),
    sa.UniqueConstraint('study_id', 'key', name=op.f('study_user_attributes_study_id_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trial_system_attributes',
    sa.Column('trial_system_attribute_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('value_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], name=op.f('trial_system_attributes_trial_id_fkey')),
    sa.PrimaryKeyConstraint('trial_system_attribute_id', name=op.f('trial_system_attributes_pkey')),
    sa.UniqueConstraint('trial_id', 'key', name=op.f('trial_system_attributes_trial_id_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
