"""changed name of type column in tasks

Revision ID: c8c39c92561b
Revises: ffa34ecc8f4f
Create Date: 2026-03-08 13:54:56.182012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8c39c92561b"
down_revision: Union[str, Sequence[str], None] = "ffa34ecc8f4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("task_type", sa.String(), nullable=False))
    op.drop_column("tasks", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("tasks", "task_type")
    # ### end Alembic commands ###
