"""added one last column

Revision ID: ffa34ecc8f4f
Revises: 29fb69dc4ab0
Create Date: 2026-03-08 01:44:11.889525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffa34ecc8f4f"
down_revision: Union[str, Sequence[str], None] = "29fb69dc4ab0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "xgboost",
        sa.Column(
            "published", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("xgboost", "published")
    # ### end Alembic commands ###
